---
title: "24_model_based_temperature_windows"
author: "Markus Min"
date: "2023-06-13"
output: html_document
---


#### Description
This script will take the modeled temperature values from script 23 and estimate temperature windows based on the reach residence time.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

# load libraries
library(here)
library(janitor)
library(tidyverse)
library(lubridate)
library(car)
library(ggthemes)
library(zoo)
library(ggpubr)
```


### load data
```{r load_data}
temp_mod_est <- read.csv(here::here("covariate_data", "for_model", "temp", "temp_mod_est.csv"))

temp_mod_est$date <- ymd(temp_mod_est$date)

# extract each dam
BON_temp_ts <- dplyr::select(temp_mod_est, date, BON)
MCN_temp_ts <- dplyr::select(temp_mod_est, date, MCN)
PRA_temp_ts <- dplyr::select(temp_mod_est, date, PRA)
RIS_temp_ts <- dplyr::select(temp_mod_est, date, RIS)
RRE_temp_ts <- dplyr::select(temp_mod_est, date, RRE)
WEL_temp_ts <- dplyr::select(temp_mod_est, date, WEL)
ICH_temp_ts <- dplyr::select(temp_mod_est, date, ICH)
LGR_temp_ts <- dplyr::select(temp_mod_est, date, LGR)

```


### calculate windows

```{r}
# so, I think that the most up to date files are in the same folders as the model runs
snake_adults_states_complete <- read.csv(here::here("stan_actual", "deteff_ESU_models", "500iter_3chain_runs", "snake", "snake_adults_states_complete.csv"), row.names = 1)
lowcol_adults_states_complete <- read.csv(here::here("stan_actual", "deteff_ESU_models", "lower_columbia", "lower_columbia_adults_states_complete.csv"), row.names = 1)
midcol_adults_states_complete <- read.csv(here::here("stan_actual", "deteff_ESU_models", "500iter_3chain_runs", "middle_columbia", "middle_columbia_adults_states_complete.csv"), row.names = 1)
uppcol_adults_states_complete <- read.csv(here::here("stan_actual", "deteff_ESU_models", "500iter_3chain_runs", "upper_columbia", "upper_columbia_adults_states_complete.csv"), row.names = 1)

# combine them all
snake_adults_states_complete %>% 
  bind_rows(., midcol_adults_states_complete) %>% 
  bind_rows(., uppcol_adults_states_complete) %>% 
  bind_rows(., lowcol_adults_states_complete) -> ASC

# now add tag code metadata, for natal origins
origin_numeric <- data.frame(natal_origin = c("Asotin_Creek", 
                                        "Clearwater_River",
                                        "Deschutes_River", 
                                        "Entiat_River", 
                                        "Fifteenmile_Creek", 
                                        "Grande_Ronde_River", 
                                        "Hood_River",
                                        "Imnaha_River",
                                        "John_Day_River", 
                                        "Methow_River", 
                                        "Okanogan_River", 
                                        "Salmon_River", 
                                        "Tucannon_River", 
                                        "Umatilla_River",
                                        "Walla_Walla_River",
                                        "Wenatchee_River", 
                                        "Yakima_River"),
                             natal_origin_numeric = seq(1,17,1))

origin_rear_actual <- read.csv(here::here("stan_actual", "origin_rear_actual.csv"), row.names = 1)
origin_rear_actual %>% 
  dplyr::rename(natal_origin_numeric = natal_origin) %>% 
  left_join(origin_numeric, by = "natal_origin_numeric") %>% 
  dplyr::select(tag_code_2, natal_origin) -> tag_code_origins

ASC %>% 
  left_join(., tag_code_origins, by = "tag_code_2") -> ASC

# also note which ESU they're from, for plotting
ESU_origins <- data.frame(natal_origin = unique(ASC$natal_origin),
                          ESU = c(rep("Snake", 6),
                                  rep("Middle Columbia", 6),
                                  rep("Upper Columbia", 4),
                                  "Lower Columbia"))

ASC %>% 
  left_join(., ESU_origins, by = "natal_origin") -> ASC

# a function that takes just one state, and finds the average amount of time to move out of that state

residence_time <- function(residence_state){
  
  # don't keep any with implicit time interpolated
  ASC %>% 
    filter(state == residence_state & tag_code_2 == lead(tag_code_2) & pathway != "implicit" & lead(pathway) != "implicit" |
             lag(state) == residence_state & tag_code_2 == lag(tag_code_2) & pathway != "implicit" & lag(pathway) != "implicit") %>% 
    mutate(date_time = ymd_hms(date_time)) -> one_state_df
  
  # make a data frame to record all of the transitions
  n_transitions <- nrow(one_state_df)/2
  passage_df <- data.frame(tag_code_2 = one_state_df$tag_code_2[seq(1,(nrow(one_state_df)-1),2)],
                           ESU = one_state_df$ESU[seq(1,(nrow(one_state_df)-1),2)],
                           natal_origin = one_state_df$natal_origin[seq(1,(nrow(one_state_df)-1),2)],
                           passage_time = NA)
  
  
  for (i in 1:nrow(passage_df)){
    passage_df$passage_time[i] <- one_state_df$date_time[(i*2)] - one_state_df$date_time[(i*2-1)]
    
  }
  
  return(passage_df)
  
}

main_mainstem_states <- c(
  "mainstem, BON to MCN",
  "mainstem, MCN to ICH or PRA",
  "mainstem, PRA to RIS",
  "mainstem, RIS to RRE",
  "mainstem, RRE to WEL",
  "mainstem, ICH to LGR",
  "mainstem, upstream of WEL",
  "mainstem, upstream of LGR")

list_quantiles <- list()

for (i in 1:length(main_mainstem_states)) {
  residence_df <- residence_time(residence_state = main_mainstem_states[i])
  
  # Look into windows - show: 1) median of the whole distribution, 
  # and what cutoff you'd need to capture 50%, 80%, and 95% of fish residence time
  quantiles <- quantile(residence_df$passage_time, probs = c(0.25, 0.5, 0.75, 0.8, 0.95))
  list_quantiles[[i]] <- quantiles

  
}

# quantiles isn't really going to work for upstream LGR and WEL, need a mixture model for those
library(mixtools)

# Upstream of Lower Granite
LGR_residence_df <- residence_time(residence_state = "mainstem, upstream of LGR")
LGR_mix <- normalmixEM(LGR_residence_df$passage_time, k = 2)

# most fish are longer residence time (81% vs. shorter residence time)
LGR_mix$lambda
# shorter residence time is 24 days, longer is 168 days
LGR_mix$mu

# show the fit
plot(LGR_mix, density=TRUE, cex.axis=1.4, cex.lab=1.4, cex.main=1.8,
      main2="Residence time, upstream of LGR", xlab2="Days")


# Upstream of Wells
WEL_residence_df <- residence_time(residence_state = "mainstem, upstream of WEL")
WEL_mix <- normalmixEM(WEL_residence_df$passage_time, k = 2)

# 51%/49% for short vs. long residence time at Wells, much different than at LGR
WEL_mix$lambda
# shorter residence time is 21 days, longer is 187 days
WEL_mix$mu

# show the fit
plot(WEL_mix, density=TRUE, cex.axis=1.4, cex.lab=1.4, cex.main=1.8,
      main2="Residence time, upstream of WEL", xlab2="Days")


# make an actual table
quantiles_table <- data.frame(reach = main_mainstem_states,
                              t25 = c(list_quantiles[[1]][1],
                                       list_quantiles[[2]][1],
                                       list_quantiles[[3]][1],
                                       list_quantiles[[4]][1],
                                       list_quantiles[[5]][1],
                                       list_quantiles[[6]][1],
                                      list_quantiles[[7]][1],
                                      list_quantiles[[8]][1]),
                              t50 = c(list_quantiles[[1]][2],
                                       list_quantiles[[2]][2],
                                       list_quantiles[[3]][2],
                                       list_quantiles[[4]][2],
                                       list_quantiles[[5]][2],
                                       list_quantiles[[6]][2],
                                      list_quantiles[[7]][2],
                                      list_quantiles[[8]][2]),
                              t75 = c(list_quantiles[[1]][3],
                                       list_quantiles[[2]][3],
                                       list_quantiles[[3]][3],
                                       list_quantiles[[4]][3],
                                       list_quantiles[[5]][3],
                                       list_quantiles[[6]][3],
                                      list_quantiles[[7]][3],
                                      list_quantiles[[8]][3]),
                              t80 = c(list_quantiles[[1]][4],
                                       list_quantiles[[2]][4],
                                       list_quantiles[[3]][4],
                                       list_quantiles[[4]][4],
                                       list_quantiles[[5]][4],
                                       list_quantiles[[6]][4],
                                      list_quantiles[[7]][4],
                                      list_quantiles[[8]][4]),
                              t95 = c(list_quantiles[[1]][5],
                                       list_quantiles[[2]][5],
                                       list_quantiles[[3]][5],
                                       list_quantiles[[4]][5],
                                       list_quantiles[[5]][5],
                                       list_quantiles[[6]][5],
                                      list_quantiles[[7]][5],
                                      list_quantiles[[8]][5]))

# write.csv(quantiles_table, here::here("covariate_data", "reach_quantiles.csv"))
```

### export temperature data using window approach

```{r}
# Re-export, using reach-specific residence time windows
# quantiles <- read.csv(here::here("covariate_data", "reach_quantiles.csv"), row.names = 1)

# round the median to nearest whole day
quantiles_table %>% 
  mutate(median = round(t50)) -> quantiles_table

# match them using outflow

# use a function
# optional argument if you want to start window at a different time
window_temp <- function(temp_data, start_window_days = 0, end_window_days){
  colnames(temp_data) <- c("date", "temp")
  
  temp_data %>% 
  mutate(window_temp = NA) -> temp_data

# loop to get all windows
for (i in 1:nrow(temp_data)){
  temp_data$window_temp[i] <- mean(subset(temp_data, date >= temp_data$date[i] + days(x = start_window_days) & date <= temp_data$date[i] + days(x = end_window_days))$temp)
}
  
  return(temp_data)
}

# Bonneville Dam, for mainstem, BON to MCN reach
BON_window_temp <- window_temp(temp_data = BON_temp_ts, end_window_days = subset(quantiles_table, reach == "mainstem, BON to MCN")$median)

# McNary Dam, for mainstem, MCN to ICH or PRA reach
MCN_window_temp <- window_temp(temp_data = MCN_temp_ts, end_window_days = subset(quantiles_table, reach == "mainstem, MCN to ICH or PRA")$median)

# PRA Dam, for PRA to RIS reach
PRA_window_temp <- window_temp(temp_data = PRA_temp_ts, end_window_days = subset(quantiles_table, reach == "mainstem, PRA to RIS")$median)

# RIS Dam, for RIS to RRE reach
RIS_window_temp <- window_temp(temp_data = RIS_temp_ts, end_window_days = subset(quantiles_table, reach == "mainstem, RIS to RRE")$median)

# RRE Dam, for RRE to WEL reach
RRE_window_temp <- window_temp(temp_data = RRE_temp_ts, end_window_days = subset(quantiles_table, reach == "mainstem, RRE to WEL")$median)

# Ice Harbor Dam, for ICH to LGR reach
ICH_window_temp <- window_temp(temp_data = ICH_temp_ts, end_window_days = subset(quantiles_table, reach == "mainstem, ICH to LGR")$median)

# Wells Dam, for upstream of WEL reach - quick fish
WEL_quick_window_temp <- window_temp(temp_data = WEL_temp_ts, 
                                     start_window_days = round(WEL_mix$mu[1] - WEL_mix$sigma[1]), 
                                     end_window_days = round(WEL_mix$mu[1] + WEL_mix$sigma[1]))

# Wells Dam, for upstream of WEL reach - slow fish
WEL_slow_window_temp <- window_temp(temp_data = WEL_temp_ts, 
                                     start_window_days = round(WEL_mix$mu[2] - WEL_mix$sigma[2]), 
                                     end_window_days = round(WEL_mix$mu[2] + WEL_mix$sigma[2]))

# Lower Granite Dam, for upstream of LGR reach - quick fish
LGR_quick_window_temp <- window_temp(temp_data = LGR_temp_ts, 
                                     start_window_days = round(LGR_mix$mu[1] - LGR_mix$sigma[1]), 
                                     end_window_days = round(LGR_mix$mu[1] + LGR_mix$sigma[1]))

# Lower Granite Dam, for upstream of LGR reach - slow fish
LGR_slow_window_temp <- window_temp(temp_data = LGR_temp_ts, 
                                     start_window_days = round(LGR_mix$mu[2] - LGR_mix$sigma[2]), 
                                     end_window_days = round(LGR_mix$mu[2] + LGR_mix$sigma[2]))

# export all of these
write.csv(BON_window_temp, here::here("covariate_data", "for_model", "temp", "BON_window_temp.csv"), row.names = FALSE)
write.csv(MCN_window_temp, here::here("covariate_data", "for_model", "temp", "MCN_window_temp.csv"), row.names = FALSE)
write.csv(PRA_window_temp, here::here("covariate_data", "for_model", "temp", "PRA_window_temp.csv"), row.names = FALSE)
write.csv(RIS_window_temp, here::here("covariate_data", "for_model", "temp", "RIS_window_temp.csv"), row.names = FALSE)
write.csv(RRE_window_temp, here::here("covariate_data", "for_model", "temp", "RRE_window_temp.csv"), row.names = FALSE)
write.csv(ICH_window_temp, here::here("covariate_data", "for_model", "temp", "ICH_window_temp.csv"), row.names = FALSE)
write.csv(WEL_quick_window_temp, here::here("covariate_data", "for_model", "temp", "WEL_quick_window_temp.csv"), row.names = FALSE)
write.csv(WEL_slow_window_temp, here::here("covariate_data", "for_model", "temp", "WEL_slow_window_temp.csv"), row.names = FALSE)
write.csv(LGR_quick_window_temp, here::here("covariate_data", "for_model", "temp", "LGR_quick_window_temp.csv"), row.names = FALSE)
write.csv(LGR_slow_window_temp, here::here("covariate_data", "for_model", "temp", "LGR_slow_window_temp.csv"), row.names = FALSE)

```

#### export in the format needed for stan
```{r}
dplyr::rename(dplyr::select(BON_window_temp, date, window_temp), BON = window_temp) %>% 
  left_join(dplyr::rename(dplyr::select(MCN_window_temp, date, window_temp), MCN = window_temp), by = "date") %>% 
  left_join(dplyr::rename(dplyr::select(PRA_window_temp, date, window_temp), PRA = window_temp), by = "date") %>% 
  left_join(dplyr::rename(dplyr::select(RIS_window_temp, date, window_temp), RIS = window_temp), by = "date") %>% 
  left_join(dplyr::rename(dplyr::select(RRE_window_temp, date, window_temp), RRE = window_temp), by = "date") %>% 
  left_join(dplyr::rename(dplyr::select(WEL_window_temp, date, window_temp), WEL = window_temp), by = "date") %>% 
  left_join(dplyr::rename(dplyr::select(ICH_window_temp, date, window_temp), ICH = window_temp), by = "date") %>% 
  left_join(dplyr::rename(dplyr::select(LGR_window_temp, date, window_temp), LGR = window_temp), by = "date") %>% 
  mutate(index = row_number()) %>% 
  relocate(index) %>% 
  dplyr::select(-date) %>% 
  column_to_rownames("index") -> window_temps

# now, z-score every column
window_temps %>% 
  mutate(BON = (BON - mean(BON))/sd(BON)) %>% 
  mutate(MCN = (MCN - mean(MCN))/sd(MCN)) %>% 
  mutate(PRA = (PRA - mean(PRA))/sd(PRA)) %>% 
  mutate(RIS = (RIS - mean(RIS))/sd(RIS)) %>% 
  mutate(RRE = (RRE - mean(RRE))/sd(RRE)) %>% 
  mutate(WEL = (WEL - mean(WEL))/sd(WEL)) %>% 
  mutate(ICH = (ICH - mean(ICH))/sd(ICH)) %>% 
  mutate(LGR = (LGR - mean(LGR))/sd(LGR)) -> window_temps

# add an empty column for the first state (that doesn't get a temperature effect)
# make sure that the order is the same is the order of states
window_temps %>% 
  mutate(MOUTH = 0) %>% 
  relocate(MOUTH) -> window_temps
  
  

write.csv(window_temps, here::here("covariate_data", "for_model", "window_temps_for_stan.csv"))
write.csv(window_temps, "/Users/markusmin/Documents/CBR/steelhead/stan_actual/rear_temp/upper_columbia/window_temps_for_stan.csv")

```
